apiVersion: v1
kind: Namespace
metadata:
  name: prd
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: react-ui
  namespace: prd
  labels:
    app: react-ui
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react-ui
  template:
    metadata:
      labels:
        app: react-ui
    spec:
      containers:
        - name: react-ui
          image: azurecrkubernetes.azurecr.io/react-simple-demo
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: react-ui-service
  namespace: prd
spec:
  type: LoadBalancer
  selector:            
    app: react-ui
  ports:
    - port: 80